import streamlit as st
import pandas as pd
import numpy as np
import os
from typing import Tuple, Optional

def generate_mock_data() -> Tuple[pd.DataFrame, pd.DataFrame]:
    """Generates professional mock data if parquets are missing."""
    
    # Mock Listings (from Data Engineering / feature/infra)
    np.random.seed(42)
    n_listings = 5000
    listings_df = pd.DataFrame({
        'Horse_ID': [f'H_{i}' for i in range(n_listings)],
        'Price': np.random.lognormal(mean=9, sigma=1, size=n_listings).clip(1000, 150000),
        'Age': np.random.normal(loc=8, scale=3, size=n_listings).clip(1, 25).astype(int),
        'Registry': np.random.choice(['KWPN', 'Hanoverian', 'Holsteiner', 'Zangersheide', 'Unknown'], n_listings, p=[0.3, 0.25, 0.2, 0.15, 0.1]),
        'Discipline': np.random.choice(['Show Jumping', 'Dressage', 'Eventing', 'Hunter'], n_listings),
        'Country': np.random.choice(['Germany', 'Netherlands', 'Belgium', 'USA', 'France'], n_listings, p=[0.3, 0.25, 0.2, 0.15, 0.1])
    })
    
    # Mock Sessions (from ML Platform / ds3)
    n_sessions = 50000
    sessions_df = pd.DataFrame({
        'user_session': [f'S_{i}' for i in range(n_sessions)],
        'horse_id': np.random.choice(listings_df['Horse_ID'], n_sessions),
        'event_type': np.random.choice(['view', 'cart', 'purchase'], n_sessions, p=[0.85, 0.12, 0.03]),
        'traffic_source': np.random.choice(['Organic', 'Paid Social', 'Direct', 'Referral'], n_sessions),
        'predicted_prob': np.random.beta(a=2, b=5, size=n_sessions),  # ML Scoring 
        'experiment_group': np.random.choice(['Control (Static)', 'Treatment (Hook)'], n_sessions)
    })
    
    return listings_df, sessions_df


@st.cache_data
def load_parquet_data() -> Tuple[pd.DataFrame, pd.DataFrame]:
    """
    Loads the parquet data generated by Data Engineering.
    If missing, falls back to generating professional Mock Data 
    to guarantee the Dashboard never breaks (Fault Tolerance).
    """
    try:
        # Resolve path robustly regardless of execution directory
        current_dir = os.path.dirname(os.path.abspath(__file__))
        data_dir = os.path.join(current_dir, '..', '..', 'data', 'clean')
        
        path_listings = os.path.join(data_dir, 'horses_listings_limpio.parquet')
        path_sessions = os.path.join(data_dir, 'horses_sessions_info.parquet')
        
        if os.path.exists(path_listings) and os.path.exists(path_sessions):
            st.sidebar.success("Conectado al Data Warehouse (Parquet) ✅")
            listings = pd.read_parquet(path_listings)
            sessions = pd.read_parquet(path_sessions)
            return listings, sessions
        else:
            st.sidebar.warning("Usando Simulated Data (Tolerancia a Fallos) ⚠️")
            return generate_mock_data()
            
    except Exception as e:
        st.sidebar.error(f"Error crítico en I/O. Forzando simulación. {e}")
        return generate_mock_data()
