import streamlit as st
import pandas as pd
import os
from typing import Tuple, Optional

@st.cache_data
def load_parquet_data() -> Tuple[Optional[pd.DataFrame], Optional[pd.DataFrame]]:
    """
    Loads the parquet data generated by Data Engineering.
    Returns:
        Tuple containing listings df and sessions df. None if files aren't found.
    """
    try:
        # Resolve path robustly regardless of execution directory
        current_dir = os.path.dirname(os.path.abspath(__file__))
        data_dir = os.path.join(current_dir, '..', '..', 'data', 'clean')
        
        path_listings = os.path.join(data_dir, 'horses_listings_limpio.parquet')
        path_sessions = os.path.join(data_dir, 'horses_sessions_info.parquet')
        
        listings = pd.read_parquet(path_listings)
        sessions = pd.read_parquet(path_sessions)
        return listings, sessions
    except Exception as e:
        st.error(f"Error cargando Data Engineering Parquets: {e}")
        return None, None
