steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'aletbm/equinelead-api'
      - '-f'
      - './deployment/Dockerfile.api'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'aletbm/equinelead-api'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'equinelead-api'
      - '--image'
      - 'docker.io/aletbm/equinelead-api:latest'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-east1'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '1Gi'

#gcloud builds submit --config deployment/cloudbuild.yaml .