steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'equinelead-api'
      - '--image'
      - 'docker.io/$_DOCKERHUB_USERNAME/equinelead-api:$_IMAGE_TAG'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-east1'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '1Gi'

# gcloud builds submit --config deployment/cloudbuild.yaml .